#-------------------------------------------------#
#           GENERAL                               #
#-------------------------------------------------#
version: 1.1.{build}-develop
  
#-------------------------------------------------#
#           ENVIRONMENT                           #
#-------------------------------------------------#
os: Visual Studio 2015
environment:
 versionPatchKey: '0.0.0-ci-replace'
 dnvmDownloadUrl: 'https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'
 dnvmVersion: '1.0.0-rc1-final'
 
#-------------------------------------------------#
#           INIT                                  #
#-------------------------------------------------#

init:
 - git config --global core.autocrlf true
 
#-------------------------------------------------#
#           INSTALL                               #
#-------------------------------------------------#

install:
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json

#-------------------------------------------------#
#           BUILD CONFIGURATION                   #
#-------------------------------------------------#

before_build:
 - ps: Write-Host "PATCHING project.json $env:versionPatchKey to $env:appveyor_build_version"
 - ps: (Get-Content src\SchwabenCode.AsyncAll\project.json).replace($env:versionPatchKey, $env:appveyor_build_version) | Set-Content src\SchwabenCode.AsyncAll\project.json
 - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString($env:dnvmDownloadUrl))}"
 - cmd: dnvm install $env:dnvmVersion
 - cmd: dnvm upgrade
 - cmd: dnvm update-self
 - cmd: dnvm list
 - cmd: dnvm use $env:dnvmVersion
 - cmd: dnu restore


build_script:
 - cmd: dnu build src\SchwabenCode.AsyncAll

#-------------------------------------------------#
#           BRANCH CONFIGURATION                  #
#-------------------------------------------------#

# configuration for "master" branch
# build in Release mode and deploy to Azure
branches:
 only:
  - develop

configuration: Release
